apiVersion: v2
name: app-chart
description: Vault secrets injection with Kubernetes Auth Method and GitHub Actions OIDC
type: application
version: 0.1.0
appVersion: "1.0.3"
maintainers:
  - name: amirhossein
    url: https://github.com/amirhosssein0